import { Inter } from "next/font/google";
import "@client/styles/globals.css";

import { AuthProvider } from "@client/context/AuthContext";
import { UserProvider } from "@client/context/UserContext";
import { NewsProvider } from "@client/context/NewsContext";

import NavBar from "@client/components/NavBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">

			<body className={inter.className}>
				<NavBar />
				<AuthProvider>
					<UserProvider>
						<NewsProvider>
							{children}
						</NewsProvider>
					</UserProvider>
				</AuthProvider>
			</body>						

		</html>
	);
}
